version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8080"
    env_file: .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
