name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # 1️⃣  Autenticación con la clave JSON del secreto
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2️⃣  Instalar gcloud ya autenticado
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: horux-crm
          install_components: 'gcloud'

      # 3️⃣  Build & push la imagen
      - name: Build & push image
        run: |
          IMAGE="europe-west4-docker.pkg.dev/horux-crm/erp-docker-repo/erp-api:${{ github.sha }}"
          gcloud builds submit --tag "$IMAGE" .
